#ifndef DISPLAY_CONSTS_H
#define DISPLAY_CONSTS_H

#define M5EPD_DISPLAY_WIDTH 960
#define M5EPD_DISPLAY_HEIGHT 540
#define M5EPD_DOCK_HEIGHT 50

#define M5EPD_BLACK 15
#define M5EPD_DARK_GREY 12
#define M5EPD_GREY 8
#define M5EPD_LIGHT_GREY 4
#define M5EPD_WHITE 0

#define BACKGROUND_X 0
#define BACKGROUND_Y 0

#define BACKGROUND_BOX_X 30
#define BACKGROUND_BOX_Y 30
#define BACKGROUND_BOX_WIDTH 900
#define BACKGROUND_BOX_HEIGHT 480
#define BACKGROUND_BOX_CORNER_RADIUS 30
#define BACKGROUND_CONTENT_CORNER_RADIUS 20
#define BACKGROUND_BOX_BORDER 10

#define BACKGROUND_SHADOW_X 15
#define BACKGROUND_SHADOW_Y 55

#define DISPLAY_CANVAS_WIDTH 960
#define DISPLAY_CANVAS_HEIGHT 540

#define DISPLAY_TITLE_X 160
#define DISPLAY_TITLE_Y 60
#define DISPLAY_TITLE_SIZE 6

#define DISPLAY_LOGO_X 90
#define DISPLAY_LOGO_Y 80
#define DISPLAY_LOGO_RADIUS 15
#define DISPLAY_LOGO_GAP 40

#define DISPLAY_DATE_X 122
#define DISPLAY_DATE_Y 114
#define DISPLAY_DATE_SIZE 3

#endif