#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H

#define KEYBOARD_INPUT_PIN_SDA 18
#define KEYBOARD_INPUT_PIN_SCL 19

#define POWER_BUTTON_PIN_IN
#define POWER_BUTTON_OUT

#define DISPLAY_WIDTH 960
#define DISPLAY_HEIGHT 540

#define TOUCH_ENABLE true

#define BATTERY_ADC_CHANNEL ADC1_CHANNEL_7 // GPIO_35
#define BATTERY_BASE_VOLATAGE 3800
#define BATTERY_SCALE 0.5 // 0.78571429
#define BATTERY_ADC_FILTER_SAMPLE 50
#define BATTERY_ALPHA 0.1

#endif